version: '3'

services:
  my_blog_api:
    build:
      context: .

    image: hub.develobeer.blog/blog-api:${TAG}
    container_name: myBlogAPI

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

    ports:
      - "80:80"